---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rpcx-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rpcx-registry
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
